### ISSUE TITLE
Long time processing - Random error thrown that file does not exist

### ISSUE THREAD

**Issue by hugomcruz** [hugomcruz/onedrive-picture-processor#6]
2021-04-25 10:48:07,675 [INFO] [root] process_file(): Processing file: 20170225_203722_ana_hcruz_720p.mp4
Traceback (most recent call last):
  File "onedrive_processor.py", line 577, in <module>
    process_onedrive_folder(origin_client, source_path, destination_client, destination_path + profile_destination_folder, config)
  File "onedrive_processor.py", line 511, in process_onedrive_folder
    process_onedrive_folder(onedrive_origin_client, new_path, onedrive_destination_client, destination_path, config)
  File "onedrive_processor.py", line 511, in process_onedrive_folder
    process_onedrive_folder(onedrive_origin_client, new_path, onedrive_destination_client, destination_path, config)
  File "onedrive_processor.py", line 511, in process_onedrive_folder
    process_onedrive_folder(onedrive_origin_client, new_path, onedrive_destination_client, destination_path, config)
  [Previous line repeated 1 more time]
  File "onedrive_processor.py", line 530, in process_onedrive_folder
    process_file(onedrive_origin_client, source_path + "/" + item["name"], onedrive_destination_client, destination_path, config)
  File "onedrive_processor.py", line 488, in process_file
    process_video_file(onedrive_origin_client, source_file, onedrive_destination_client, destination_path, config)
  File "onedrive_processor.py", line 415, in process_video_file
    new_filename = video_filename(filename)
  File "onedrive_processor.py", line 386, in video_filename
    date_obj = video_creation_datetime(filename)
  File "/app/bin/onedrive-picture-processor-main/video_processing.py", line 33, in video_creation_datetime
    metadata=FFProbe(filepath)
  File "/app/lib/ffprobe-python-master/ffprobe/ffprobe.py", line 124, in __init__
    raise IOError('No such media file ' + self.path_to_video)
OSError: No such media file 20170225_203722_ana_hcruz_720p.mp4
[root@scw-01 ~]# podman start onedrive-processor -a
2021-04-25 11:01:57,535 [INFO] [root] Started processing the Onedrive files...
2021-04-25 11:01:57,540 [INFO] [root] OneDrive - Initialized

**Comment by hugomcruz** [comment]
Potential error due to lack of error handling on the output of the file download.
